### ISSUE TITLE
Pls update the Wiki!

### ISSUE THREAD

**Issue by SparkleArts** [pufmat/skillsmod#100]
Really I cannot use the Wiki because the Wiki is completely outdated no important Information which Stats are available. There is so much Information lost that needed to actually worth the time to read the Wiki.

I don't say anything less.

**Comment by pufmat** [comment]
Information on the wiki should be up-to-date with the latest version of the mod, except some pages that explicitly state that they are not.

> the Wiki is completely outdated

Please provide which pages you have found outdated (except these which are marked as such).

> no important Information which Stats are available

What do you mean by it? If you are looking for statistics, they are listed on Minecraft Wiki: https://minecraft.wiki/w/Statistics

> There is so much Information lost 

Please provide what information you have found lacking. Sometimes when a lot of things are added in an update I may easily miss something.

I'll do my best to improve the wiki, but keep in mind that writing it takes some time.

**Comment by xhytenzhi** [comment]
Hello,

i would like to see an example of how to add Pufferfish_Attributes to the Skilltree. i always receive error.
Here is one example how i tried it:

[...]
	"resistance+1%": {
		"title": "+1% Resistance",
		"icon": {
			"type": "effect",
			"data": {
				"effect": "resistance"
			}
		},
		"rewards": [
			{
				"type": "puffish_attributes:attribute",
				"data": {
					"attribute": "puffish_attributes:player.ranged_resistance",
					"value": 0.01,
					"operation": "multiply_total"
				}
			}
		]
[...]

I added some other definitions, based on original ones like health +6 instead of 2. this works fine..
I cant find any wiki entry with an example of using the other attributes :)

**Well, already found the issue. [ "type": "puffish_attributes:attribute", ] should stay as puffish_skills:attribute
