### ISSUE TITLE
Custom Icon resource location

### ISSUE THREAD

**Issue by Paulino0o** [pufmat/skillsmod#106]
I am having trouble figuring out the path to the folder where I have to put my custom icon png files.

On the wiki (https://puffish.net/skillsmod/docs/creators/configuration/icons#texture-icon), it says "The following example uses texture located in textures/icons from a data pack named example.". I tried that path, and all the variations I could think of and can't get it to work.

Could you specify the whole datapack path to make it easier?

**Comment by pufmat** [comment]
The documentation is wrong here. You actually need to put that custom icon in a resource pack. This is because data packs can't add assets.

If you want to keep both data and assets in one place then consider making a code less mod which can work as a resource pack and a data pack. You can use a new [Template Generator](https://puffish.net/skillsmod/docs/creators/template-generator) to easily create all files needed to make such code less mod.

**Comment by Paulino0o** [comment]
I tried putting it on a resourcepack as well.

But tried again now and it worked. Maybe I forgot to reload the textures when I tried it the first time. 

Anyways, its fixed, thanks for the help!
